---

- name: Copy CA certificate file to remote host
  copy:
    src: "ssl/ca.crt"
    dest: "/etc/ssl/ca.crt"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0644"
  when: consul_ssl

- name: Copy certificate file to remote host
  copy:
    src: "ssl/ssl.crt"
    dest: "/etc/ssl/ssl.crt"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0644"
  when: consul_ssl

- name: Copy private key file to remote host
  copy:
    src: "ssl/ssl.key"
    dest: "/etc/ssl/ssl.key"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0400"
  when: consul_ssl
