---

  - include_tasks: 01-setup-angie-repo.yaml
  - include_tasks: 02-copy-tls-certs.yaml
  - include_tasks: 03-setup-consul-lb.yaml
  - include_tasks: 04-deploy-angie.yaml
  - meta: flush_handlers
  - include_tasks: tasks/05-helthcheck.yaml
